search: Handle unexpected errors
Bad search strings cause the escape_string method of MySQL to blow up.

UnicodeEncodeError: 'ascii' codec can't encode characters in position
0-6: ordinal not in range(128)

Catch these errors and display an obtuse error message.